id: TASK-1773994223129-收缩剩余-Bun-first-工具链残留
title: 收缩剩余-Bun-first-工具链残留
status: done
archived: false
created_at: '2026-03-20T08:10:23.129Z'
updated_at: '2026-03-20T08:14:46.587Z'
related_repos: []
depends_on: []
blocked_by: []
tags: []
